2018-08-19 14:54:52 ERROR BankDaoJdbc:41 - ERROR: relation "bank_user" does not exist
  Position: 13
2018-08-19 14:54:52 ERROR BankDaoJdbc:43 - org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
2018-08-19 14:54:52 ERROR BankDaoJdbc:43 - org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
2018-08-19 14:54:52 ERROR BankDaoJdbc:43 - org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
2018-08-19 14:54:52 ERROR BankDaoJdbc:43 - org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
2018-08-19 14:54:52 ERROR BankDaoJdbc:43 - org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
2018-08-19 14:54:52 ERROR BankDaoJdbc:43 - org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
2018-08-19 14:54:52 ERROR BankDaoJdbc:43 - org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
2018-08-19 14:54:52 ERROR BankDaoJdbc:43 - com.revature.daos.BankDaoJdbc.createUser(BankDaoJdbc.java:37)
2018-08-19 14:54:52 ERROR BankDaoJdbc:43 - com.revature.project0.Project_0_DClarkyD.RegisterGuest.start(RegisterGuest.java:35)
2018-08-19 14:54:52 ERROR BankDaoJdbc:43 - com.revature.project0.Project_0_DClarkyD.ClassLauncher.main(ClassLauncher.java:10)
2018-08-19 14:54:52 WARN  BankDaoJdbc:45 - failed to create new user
2018-08-19 15:17:07 ERROR BankDaoJdbc:41 - ERROR: relation "bank_user" does not exist
  Position: 13
2018-08-19 15:17:07 ERROR BankDaoJdbc:43 - org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
2018-08-19 15:17:07 ERROR BankDaoJdbc:43 - org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
2018-08-19 15:17:07 ERROR BankDaoJdbc:43 - org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
2018-08-19 15:17:07 ERROR BankDaoJdbc:43 - org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
2018-08-19 15:17:07 ERROR BankDaoJdbc:43 - org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
2018-08-19 15:17:07 ERROR BankDaoJdbc:43 - org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
2018-08-19 15:17:07 ERROR BankDaoJdbc:43 - org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
2018-08-19 15:17:07 ERROR BankDaoJdbc:43 - com.revature.daos.BankDaoJdbc.createUser(BankDaoJdbc.java:37)
2018-08-19 15:17:07 ERROR BankDaoJdbc:43 - com.revature.project0.Project_0_DClarkyD.RegisterGuest.start(RegisterGuest.java:35)
2018-08-19 15:17:07 ERROR BankDaoJdbc:43 - com.revature.project0.Project_0_DClarkyD.ClassLauncher.main(ClassLauncher.java:10)
2018-08-19 15:17:07 WARN  BankDaoJdbc:45 - failed to create new user
2018-08-19 16:20:32 ERROR BankDaoJdbc:41 - ERROR: relation "bank_user" does not exist
  Position: 13
2018-08-19 16:20:32 ERROR BankDaoJdbc:43 - org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
2018-08-19 16:20:32 ERROR BankDaoJdbc:43 - org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
2018-08-19 16:20:32 ERROR BankDaoJdbc:43 - org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
2018-08-19 16:20:32 ERROR BankDaoJdbc:43 - org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
2018-08-19 16:20:32 ERROR BankDaoJdbc:43 - org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
2018-08-19 16:20:32 ERROR BankDaoJdbc:43 - org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
2018-08-19 16:20:32 ERROR BankDaoJdbc:43 - org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
2018-08-19 16:20:32 ERROR BankDaoJdbc:43 - com.revature.daos.BankDaoJdbc.createUser(BankDaoJdbc.java:37)
2018-08-19 16:20:32 ERROR BankDaoJdbc:43 - com.revature.project0.Project_0_DClarkyD.RegisterGuest.start(RegisterGuest.java:35)
2018-08-19 16:20:32 ERROR BankDaoJdbc:43 - com.revature.project0.Project_0_DClarkyD.ClassLauncher.main(ClassLauncher.java:10)
2018-08-19 16:20:32 WARN  BankDaoJdbc:45 - failed to create new user
2018-08-19 16:27:15 ERROR BankDaoJdbc:41 - FATAL: password authentication failed for user "postgres"
2018-08-19 16:27:15 ERROR BankDaoJdbc:43 - org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:473)
2018-08-19 16:27:15 ERROR BankDaoJdbc:43 - org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:205)
2018-08-19 16:27:15 ERROR BankDaoJdbc:43 - org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
2018-08-19 16:27:15 ERROR BankDaoJdbc:43 - org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
2018-08-19 16:27:15 ERROR BankDaoJdbc:43 - org.postgresql.Driver.makeConnection(Driver.java:452)
2018-08-19 16:27:15 ERROR BankDaoJdbc:43 - org.postgresql.Driver.connect(Driver.java:254)
2018-08-19 16:27:15 ERROR BankDaoJdbc:43 - java.sql.DriverManager.getConnection(Unknown Source)
2018-08-19 16:27:15 ERROR BankDaoJdbc:43 - java.sql.DriverManager.getConnection(Unknown Source)
2018-08-19 16:27:15 ERROR BankDaoJdbc:43 - com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:29)
2018-08-19 16:27:15 ERROR BankDaoJdbc:43 - com.revature.daos.BankDaoJdbc.createUser(BankDaoJdbc.java:27)
2018-08-19 16:27:15 ERROR BankDaoJdbc:43 - com.revature.project0.Project_0_DClarkyD.RegisterGuest.start(RegisterGuest.java:35)
2018-08-19 16:27:15 ERROR BankDaoJdbc:43 - com.revature.project0.Project_0_DClarkyD.ClassLauncher.main(ClassLauncher.java:10)
2018-08-19 16:27:15 WARN  BankDaoJdbc:45 - failed to create new user
2018-08-19 16:28:33 TRACE BankDaoJdbc:38 - 1 records created
2018-08-19 16:31:56 TRACE BankDaoJdbc:38 - 1 records created
2018-08-19 16:32:22 WARN  BankDaoJdbc:69 - failed to find user with provided credentials from the db
2018-08-19 16:32:46 ERROR BankDaoJdbc:41 - ERROR: duplicate key value violates unique constraint "bank_user_pkey"
  Detail: Key (userid)=(0) already exists.
2018-08-19 16:32:46 ERROR BankDaoJdbc:43 - org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
2018-08-19 16:32:46 ERROR BankDaoJdbc:43 - org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
2018-08-19 16:32:46 ERROR BankDaoJdbc:43 - org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
2018-08-19 16:32:46 ERROR BankDaoJdbc:43 - org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
2018-08-19 16:32:46 ERROR BankDaoJdbc:43 - org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
2018-08-19 16:32:46 ERROR BankDaoJdbc:43 - org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
2018-08-19 16:32:46 ERROR BankDaoJdbc:43 - org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
2018-08-19 16:32:46 ERROR BankDaoJdbc:43 - com.revature.daos.BankDaoJdbc.createUser(BankDaoJdbc.java:37)
2018-08-19 16:32:46 ERROR BankDaoJdbc:43 - com.revature.project0.Project_0_DClarkyD.RegisterGuest.start(RegisterGuest.java:35)
2018-08-19 16:32:46 ERROR BankDaoJdbc:43 - com.revature.project0.Project_0_DClarkyD.ClassLauncher.main(ClassLauncher.java:10)
2018-08-19 16:32:46 WARN  BankDaoJdbc:45 - failed to create new user
2018-08-19 16:39:39 ERROR BankDaoJdbc:42 - No value specified for parameter 1.
2018-08-19 16:39:39 ERROR BankDaoJdbc:44 - org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:257)
2018-08-19 16:39:39 ERROR BankDaoJdbc:44 - org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:290)
2018-08-19 16:39:39 ERROR BankDaoJdbc:44 - org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
2018-08-19 16:39:39 ERROR BankDaoJdbc:44 - org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
2018-08-19 16:39:39 ERROR BankDaoJdbc:44 - org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
2018-08-19 16:39:39 ERROR BankDaoJdbc:44 - org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
2018-08-19 16:39:39 ERROR BankDaoJdbc:44 - com.revature.daos.BankDaoJdbc.createUser(BankDaoJdbc.java:38)
2018-08-19 16:39:39 ERROR BankDaoJdbc:44 - com.revature.project0.Project_0_DClarkyD.RegisterGuest.start(RegisterGuest.java:35)
2018-08-19 16:39:39 ERROR BankDaoJdbc:44 - com.revature.project0.Project_0_DClarkyD.ClassLauncher.main(ClassLauncher.java:10)
2018-08-19 16:39:39 WARN  BankDaoJdbc:46 - failed to create new user
2018-08-19 16:40:11 ERROR BankDaoJdbc:42 - ERROR: column "userid" is of type integer but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 96
2018-08-19 16:40:11 ERROR BankDaoJdbc:44 - org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
2018-08-19 16:40:11 ERROR BankDaoJdbc:44 - org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
2018-08-19 16:40:11 ERROR BankDaoJdbc:44 - org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
2018-08-19 16:40:11 ERROR BankDaoJdbc:44 - org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
2018-08-19 16:40:11 ERROR BankDaoJdbc:44 - org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
2018-08-19 16:40:11 ERROR BankDaoJdbc:44 - org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
2018-08-19 16:40:11 ERROR BankDaoJdbc:44 - org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
2018-08-19 16:40:11 ERROR BankDaoJdbc:44 - com.revature.daos.BankDaoJdbc.createUser(BankDaoJdbc.java:38)
2018-08-19 16:40:11 ERROR BankDaoJdbc:44 - com.revature.project0.Project_0_DClarkyD.RegisterGuest.start(RegisterGuest.java:35)
2018-08-19 16:40:11 ERROR BankDaoJdbc:44 - com.revature.project0.Project_0_DClarkyD.ClassLauncher.main(ClassLauncher.java:10)
2018-08-19 16:40:11 WARN  BankDaoJdbc:46 - failed to create new user
2018-08-19 16:40:48 ERROR BankDaoJdbc:42 - ERROR: INSERT has more expressions than target columns
  Position: 104
2018-08-19 16:40:48 ERROR BankDaoJdbc:44 - org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
2018-08-19 16:40:48 ERROR BankDaoJdbc:44 - org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
2018-08-19 16:40:48 ERROR BankDaoJdbc:44 - org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
2018-08-19 16:40:48 ERROR BankDaoJdbc:44 - org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
2018-08-19 16:40:48 ERROR BankDaoJdbc:44 - org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
2018-08-19 16:40:48 ERROR BankDaoJdbc:44 - org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
2018-08-19 16:40:48 ERROR BankDaoJdbc:44 - org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
2018-08-19 16:40:48 ERROR BankDaoJdbc:44 - com.revature.daos.BankDaoJdbc.createUser(BankDaoJdbc.java:38)
2018-08-19 16:40:48 ERROR BankDaoJdbc:44 - com.revature.project0.Project_0_DClarkyD.RegisterGuest.start(RegisterGuest.java:35)
2018-08-19 16:40:48 ERROR BankDaoJdbc:44 - com.revature.project0.Project_0_DClarkyD.ClassLauncher.main(ClassLauncher.java:10)
2018-08-19 16:40:48 WARN  BankDaoJdbc:46 - failed to create new user
2018-08-19 16:41:17 TRACE BankDaoJdbc:39 - 1 records created
2018-08-19 16:46:57 WARN  BankDaoJdbc:70 - failed to find user with provided credentials from the db
2018-08-20 10:17:00 TRACE BankDaoJdbc:39 - 1 records created
2018-08-20 10:18:32 WARN  BankDaoJdbc:70 - failed to find user with provided credentials from the db
2018-08-20 10:18:40 WARN  BankDaoJdbc:70 - failed to find user with provided credentials from the db
2018-08-20 10:18:49 WARN  BankDaoJdbc:70 - failed to find user with provided credentials from the db
2018-08-20 10:18:53 WARN  BankDaoJdbc:70 - failed to find user with provided credentials from the db
2018-08-20 12:48:50 ERROR BankDaoJdbc:133 - ERROR: operator does not exist: character varying = double precision
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 58
2018-08-20 12:48:50 ERROR BankDaoJdbc:135 - org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
2018-08-20 12:48:50 ERROR BankDaoJdbc:135 - org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
2018-08-20 12:48:50 ERROR BankDaoJdbc:135 - org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
2018-08-20 12:48:50 ERROR BankDaoJdbc:135 - org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
2018-08-20 12:48:50 ERROR BankDaoJdbc:135 - org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
2018-08-20 12:48:50 ERROR BankDaoJdbc:135 - org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
2018-08-20 12:48:50 ERROR BankDaoJdbc:135 - org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
2018-08-20 12:48:50 ERROR BankDaoJdbc:135 - com.revature.daos.BankDaoJdbc.updateCurrency(BankDaoJdbc.java:129)
2018-08-20 12:48:50 ERROR BankDaoJdbc:135 - com.revature.project0.Project_0_DClarkyD.DepositScreen.start(DepositScreen.java:33)
2018-08-20 12:48:50 ERROR BankDaoJdbc:135 - com.revature.project0.Project_0_DClarkyD.ClassLauncher.main(ClassLauncher.java:10)
2018-08-20 12:48:50 WARN  BankDaoJdbc:137 - failed to create new user
2018-08-20 12:49:27 TRACE BankDaoJdbc:131 - 3 records created
2018-08-20 12:49:51 TRACE BankDaoJdbc:131 - 3 records created
2018-08-20 12:53:41 TRACE BankDaoJdbc:131 - 3 records created
2018-08-20 12:54:31 TRACE BankDaoJdbc:131 - 3 records created
2018-08-20 12:56:40 TRACE BankDaoJdbc:131 - 3 records created
2018-08-20 12:56:55 TRACE BankDaoJdbc:131 - 3 records created
2018-08-20 13:25:32 TRACE BankDaoJdbc:131 - 3 records created
2018-08-20 13:25:40 TRACE BankDaoJdbc:131 - 3 records created
2018-08-20 13:26:40 TRACE BankDaoJdbc:39 - 1 records created
2018-08-20 13:26:56 TRACE BankDaoJdbc:39 - 1 records created
2018-08-20 13:27:08 WARN  BankDaoJdbc:101 - failed to find user with provided credentials from the db
2018-08-20 13:27:26 TRACE BankDaoJdbc:131 - 4 records created
2018-08-20 13:29:21 WARN  BankDaoJdbc:101 - failed to find user with provided credentials from the db
2018-08-20 13:29:30 TRACE BankDaoJdbc:131 - 1 records created
2018-08-20 13:34:11 TRACE BankDaoJdbc:39 - 1 records created
2018-08-20 13:36:14 TRACE BankDaoJdbc:131 - 1 records created
2018-08-20 13:42:32 WARN  BankDaoJdbc:70 - failed to find user with provided credentials from the db
2018-08-20 13:42:48 TRACE BankDaoJdbc:39 - 1 records created
2018-08-20 13:46:35 WARN  HistoryDaoJdbc:93 - failed to find user with provided credentials from the db
2018-08-20 13:46:36 TRACE BankDaoJdbc:131 - 4 records created
2018-08-20 14:04:04 TRACE BankDaoJdbc:39 - 1 records created
2018-08-20 14:44:49 ERROR BankDaoJdbc:42 - ERROR: column "currency_amount" of relation "bank_user" does not exist
  Position: 64
2018-08-20 14:44:49 ERROR BankDaoJdbc:44 - org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
2018-08-20 14:44:49 ERROR BankDaoJdbc:44 - org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
2018-08-20 14:44:49 ERROR BankDaoJdbc:44 - org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
2018-08-20 14:44:49 ERROR BankDaoJdbc:44 - org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
2018-08-20 14:44:49 ERROR BankDaoJdbc:44 - org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
2018-08-20 14:44:49 ERROR BankDaoJdbc:44 - org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
2018-08-20 14:44:49 ERROR BankDaoJdbc:44 - org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
2018-08-20 14:44:49 ERROR BankDaoJdbc:44 - com.revature.daos.BankDaoJdbc.createUser(BankDaoJdbc.java:38)
2018-08-20 14:44:49 ERROR BankDaoJdbc:44 - com.revature.project0.Project_0_DClarkyD.RegisterGuest.start(RegisterGuest.java:35)
2018-08-20 14:44:49 ERROR BankDaoJdbc:44 - com.revature.project0.Project_0_DClarkyD.ClassLauncher.main(ClassLauncher.java:10)
2018-08-20 14:44:49 WARN  BankDaoJdbc:46 - failed to create new user
2018-08-20 14:44:49 ERROR HistoryDaoJdbc:54 - No value specified for parameter 3.
2018-08-20 14:44:49 ERROR HistoryDaoJdbc:56 - org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:257)
2018-08-20 14:44:49 ERROR HistoryDaoJdbc:56 - org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:290)
2018-08-20 14:44:49 ERROR HistoryDaoJdbc:56 - org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
2018-08-20 14:44:49 ERROR HistoryDaoJdbc:56 - org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
2018-08-20 14:44:49 ERROR HistoryDaoJdbc:56 - org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
2018-08-20 14:44:49 ERROR HistoryDaoJdbc:56 - org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
2018-08-20 14:44:49 ERROR HistoryDaoJdbc:56 - com.revature.daos.HistoryDaoJdbc.createHistory(HistoryDaoJdbc.java:50)
2018-08-20 14:44:49 ERROR HistoryDaoJdbc:56 - com.revature.project0.Project_0_DClarkyD.RegisterGuest.start(RegisterGuest.java:36)
2018-08-20 14:44:49 ERROR HistoryDaoJdbc:56 - com.revature.project0.Project_0_DClarkyD.ClassLauncher.main(ClassLauncher.java:10)
2018-08-20 14:44:49 WARN  HistoryDaoJdbc:58 - failed to create new user
2018-08-20 14:52:44 WARN  BankDaoJdbc:69 - failed to find user with provided credentials from the db
2018-08-20 14:52:57 TRACE BankDaoJdbc:38 - 1 records created
2018-08-20 14:54:48 TRACE BankDaoJdbc:38 - 1 records created
2018-08-20 14:54:48 ERROR HistoryDaoJdbc:56 - ERROR: relation "bank_history" does not exist
  Position: 13
2018-08-20 14:54:48 ERROR HistoryDaoJdbc:58 - org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
2018-08-20 14:54:48 ERROR HistoryDaoJdbc:58 - org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
2018-08-20 14:54:48 ERROR HistoryDaoJdbc:58 - org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
2018-08-20 14:54:48 ERROR HistoryDaoJdbc:58 - org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
2018-08-20 14:54:48 ERROR HistoryDaoJdbc:58 - org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
2018-08-20 14:54:48 ERROR HistoryDaoJdbc:58 - org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
2018-08-20 14:54:48 ERROR HistoryDaoJdbc:58 - org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
2018-08-20 14:54:48 ERROR HistoryDaoJdbc:58 - com.revature.daos.HistoryDaoJdbc.createHistory(HistoryDaoJdbc.java:52)
2018-08-20 14:54:48 ERROR HistoryDaoJdbc:58 - com.revature.project0.Project_0_DClarkyD.RegisterGuest.start(RegisterGuest.java:39)
2018-08-20 14:54:48 ERROR HistoryDaoJdbc:58 - com.revature.project0.Project_0_DClarkyD.ClassLauncher.main(ClassLauncher.java:10)
2018-08-20 14:54:48 WARN  HistoryDaoJdbc:60 - failed to create new user
2018-08-20 14:55:40 TRACE BankDaoJdbc:38 - 1 records created
2018-08-20 14:55:41 ERROR HistoryDaoJdbc:56 - ERROR: column "change_time" is of type time without time zone but expression is of type double precision
  Hint: You will need to rewrite or cast the expression.
  Position: 104
2018-08-20 14:55:41 ERROR HistoryDaoJdbc:58 - org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
2018-08-20 14:55:41 ERROR HistoryDaoJdbc:58 - org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
2018-08-20 14:55:41 ERROR HistoryDaoJdbc:58 - org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
2018-08-20 14:55:41 ERROR HistoryDaoJdbc:58 - org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
2018-08-20 14:55:41 ERROR HistoryDaoJdbc:58 - org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
2018-08-20 14:55:41 ERROR HistoryDaoJdbc:58 - org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
2018-08-20 14:55:41 ERROR HistoryDaoJdbc:58 - org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
2018-08-20 14:55:41 ERROR HistoryDaoJdbc:58 - com.revature.daos.HistoryDaoJdbc.createHistory(HistoryDaoJdbc.java:52)
2018-08-20 14:55:41 ERROR HistoryDaoJdbc:58 - com.revature.project0.Project_0_DClarkyD.RegisterGuest.start(RegisterGuest.java:39)
2018-08-20 14:55:41 ERROR HistoryDaoJdbc:58 - com.revature.project0.Project_0_DClarkyD.ClassLauncher.main(ClassLauncher.java:10)
2018-08-20 14:55:41 WARN  HistoryDaoJdbc:60 - failed to create new user
2018-08-20 15:00:22 TRACE BankDaoJdbc:38 - 1 records created
2018-08-20 15:00:22 ERROR HistoryDaoJdbc:56 - ERROR: column "change_time" is of type time without time zone but expression is of type double precision
  Hint: You will need to rewrite or cast the expression.
  Position: 104
2018-08-20 15:00:22 ERROR HistoryDaoJdbc:58 - org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
2018-08-20 15:00:22 ERROR HistoryDaoJdbc:58 - org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
2018-08-20 15:00:22 ERROR HistoryDaoJdbc:58 - org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
2018-08-20 15:00:22 ERROR HistoryDaoJdbc:58 - org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
2018-08-20 15:00:22 ERROR HistoryDaoJdbc:58 - org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
2018-08-20 15:00:22 ERROR HistoryDaoJdbc:58 - org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
2018-08-20 15:00:22 ERROR HistoryDaoJdbc:58 - org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
2018-08-20 15:00:22 ERROR HistoryDaoJdbc:58 - com.revature.daos.HistoryDaoJdbc.createHistory(HistoryDaoJdbc.java:52)
2018-08-20 15:00:22 ERROR HistoryDaoJdbc:58 - com.revature.project0.Project_0_DClarkyD.RegisterGuest.start(RegisterGuest.java:39)
2018-08-20 15:00:22 ERROR HistoryDaoJdbc:58 - com.revature.project0.Project_0_DClarkyD.ClassLauncher.main(ClassLauncher.java:10)
2018-08-20 15:00:22 WARN  HistoryDaoJdbc:60 - failed to create new user
2018-08-20 15:02:54 TRACE BankDaoJdbc:38 - 1 records created
2018-08-20 15:02:54 ERROR HistoryDaoJdbc:56 - ERROR: column "change_time" is of type time without time zone but expression is of type double precision
  Hint: You will need to rewrite or cast the expression.
  Position: 104
2018-08-20 15:02:54 ERROR HistoryDaoJdbc:58 - org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
2018-08-20 15:02:54 ERROR HistoryDaoJdbc:58 - org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
2018-08-20 15:02:54 ERROR HistoryDaoJdbc:58 - org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
2018-08-20 15:02:54 ERROR HistoryDaoJdbc:58 - org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
2018-08-20 15:02:54 ERROR HistoryDaoJdbc:58 - org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
2018-08-20 15:02:54 ERROR HistoryDaoJdbc:58 - org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
2018-08-20 15:02:54 ERROR HistoryDaoJdbc:58 - org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
2018-08-20 15:02:54 ERROR HistoryDaoJdbc:58 - com.revature.daos.HistoryDaoJdbc.createHistory(HistoryDaoJdbc.java:52)
2018-08-20 15:02:54 ERROR HistoryDaoJdbc:58 - com.revature.project0.Project_0_DClarkyD.RegisterGuest.start(RegisterGuest.java:39)
2018-08-20 15:02:54 ERROR HistoryDaoJdbc:58 - com.revature.project0.Project_0_DClarkyD.ClassLauncher.main(ClassLauncher.java:10)
2018-08-20 15:02:54 WARN  HistoryDaoJdbc:60 - failed to create new user
2018-08-20 15:05:46 TRACE BankDaoJdbc:38 - 1 records created
2018-08-20 15:05:46 ERROR HistoryDaoJdbc:56 - ERROR: column "change_time" is of type time without time zone but expression is of type double precision
  Hint: You will need to rewrite or cast the expression.
  Position: 104
2018-08-20 15:05:46 ERROR HistoryDaoJdbc:58 - org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
2018-08-20 15:05:46 ERROR HistoryDaoJdbc:58 - org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
2018-08-20 15:05:46 ERROR HistoryDaoJdbc:58 - org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
2018-08-20 15:05:46 ERROR HistoryDaoJdbc:58 - org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
2018-08-20 15:05:46 ERROR HistoryDaoJdbc:58 - org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
2018-08-20 15:05:46 ERROR HistoryDaoJdbc:58 - org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
2018-08-20 15:05:46 ERROR HistoryDaoJdbc:58 - org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
2018-08-20 15:05:46 ERROR HistoryDaoJdbc:58 - com.revature.daos.HistoryDaoJdbc.createHistory(HistoryDaoJdbc.java:52)
2018-08-20 15:05:46 ERROR HistoryDaoJdbc:58 - com.revature.project0.Project_0_DClarkyD.RegisterGuest.start(RegisterGuest.java:39)
2018-08-20 15:05:46 ERROR HistoryDaoJdbc:58 - com.revature.project0.Project_0_DClarkyD.ClassLauncher.main(ClassLauncher.java:10)
2018-08-20 15:05:46 WARN  HistoryDaoJdbc:60 - failed to create new user
2018-08-20 15:18:37 TRACE BankDaoJdbc:38 - 1 records created
2018-08-20 15:18:37 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 15:21:07 TRACE BankDaoJdbc:38 - 1 records created
2018-08-20 15:21:07 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 15:30:45 TRACE BankDaoJdbc:38 - 1 records created
2018-08-20 15:30:45 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 15:31:54 TRACE BankDaoJdbc:38 - 1 records created
2018-08-20 15:31:55 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 15:33:26 TRACE BankDaoJdbc:38 - 1 records created
2018-08-20 15:33:27 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 15:33:36 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 15:37:17 TRACE BankDaoJdbc:38 - 1 records created
2018-08-20 15:37:17 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 15:38:03 TRACE BankDaoJdbc:38 - 1 records created
2018-08-20 15:38:03 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 15:38:12 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 15:39:15 TRACE BankDaoJdbc:38 - 1 records created
2018-08-20 15:39:15 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 15:39:23 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 15:40:21 TRACE BankDaoJdbc:38 - 1 records created
2018-08-20 15:40:21 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 15:40:33 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 15:40:34 ERROR HistoryDaoJdbc:32 - ERROR: column "currency_balance" of relation "bank_transactions" does not exist
  Position: 30
2018-08-20 15:40:34 ERROR HistoryDaoJdbc:34 - org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
2018-08-20 15:40:34 ERROR HistoryDaoJdbc:34 - org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
2018-08-20 15:40:34 ERROR HistoryDaoJdbc:34 - org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
2018-08-20 15:40:34 ERROR HistoryDaoJdbc:34 - org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
2018-08-20 15:40:34 ERROR HistoryDaoJdbc:34 - org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
2018-08-20 15:40:34 ERROR HistoryDaoJdbc:34 - org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
2018-08-20 15:40:34 ERROR HistoryDaoJdbc:34 - org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
2018-08-20 15:40:34 ERROR HistoryDaoJdbc:34 - com.revature.daos.HistoryDaoJdbc.updateHistory(HistoryDaoJdbc.java:28)
2018-08-20 15:40:34 ERROR HistoryDaoJdbc:34 - com.revature.project0.Project_0_DClarkyD.DepositScreen.start(DepositScreen.java:37)
2018-08-20 15:40:34 ERROR HistoryDaoJdbc:34 - com.revature.project0.Project_0_DClarkyD.ClassLauncher.main(ClassLauncher.java:10)
2018-08-20 15:40:34 WARN  HistoryDaoJdbc:36 - failed to create new user
2018-08-20 15:43:06 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 15:43:07 TRACE HistoryDaoJdbc:29 - 14 records created
2018-08-20 15:51:00 TRACE BankDaoJdbc:38 - 1 records created
2018-08-20 15:51:00 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 15:51:04 WARN  BankDaoJdbc:69 - failed to find user with provided credentials from the db
2018-08-20 15:51:15 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 15:51:15 TRACE HistoryDaoJdbc:29 - 16 records created
2018-08-20 15:56:55 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 15:56:56 TRACE HistoryDaoJdbc:29 - 17 records created
2018-08-20 15:57:50 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 15:57:51 TRACE HistoryDaoJdbc:29 - 18 records created
2018-08-20 16:02:03 TRACE BankDaoJdbc:38 - 1 records created
2018-08-20 16:02:04 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 16:02:06 WARN  BankDaoJdbc:69 - failed to find user with provided credentials from the db
2018-08-20 16:02:19 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 16:02:20 TRACE HistoryDaoJdbc:29 - 20 records created
2018-08-20 16:29:10 ERROR BankDaoJdbc:53 - No value specified for parameter 1.
2018-08-20 16:29:10 ERROR BankDaoJdbc:55 - org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:257)
2018-08-20 16:29:10 ERROR BankDaoJdbc:55 - org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:290)
2018-08-20 16:29:10 ERROR BankDaoJdbc:55 - org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
2018-08-20 16:29:10 ERROR BankDaoJdbc:55 - org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
2018-08-20 16:29:10 ERROR BankDaoJdbc:55 - org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
2018-08-20 16:29:10 ERROR BankDaoJdbc:55 - org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)
2018-08-20 16:29:10 ERROR BankDaoJdbc:55 - com.revature.daos.BankDaoJdbc.createUser(BankDaoJdbc.java:42)
2018-08-20 16:29:10 ERROR BankDaoJdbc:55 - com.revature.project0.Project_0_DClarkyD.RegisterGuest.start(RegisterGuest.java:38)
2018-08-20 16:29:10 ERROR BankDaoJdbc:55 - com.revature.project0.Project_0_DClarkyD.ClassLauncher.main(ClassLauncher.java:10)
2018-08-20 16:29:10 WARN  BankDaoJdbc:57 - failed to create new user
2018-08-20 16:29:11 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 16:31:22 ERROR BankDaoJdbc:54 - No value specified for parameter 1.
2018-08-20 16:31:22 ERROR BankDaoJdbc:56 - org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:257)
2018-08-20 16:31:22 ERROR BankDaoJdbc:56 - org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:290)
2018-08-20 16:31:22 ERROR BankDaoJdbc:56 - org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
2018-08-20 16:31:22 ERROR BankDaoJdbc:56 - org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
2018-08-20 16:31:22 ERROR BankDaoJdbc:56 - org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
2018-08-20 16:31:22 ERROR BankDaoJdbc:56 - org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)
2018-08-20 16:31:22 ERROR BankDaoJdbc:56 - com.revature.daos.BankDaoJdbc.createUser(BankDaoJdbc.java:42)
2018-08-20 16:31:22 ERROR BankDaoJdbc:56 - com.revature.project0.Project_0_DClarkyD.RegisterGuest.start(RegisterGuest.java:38)
2018-08-20 16:31:22 ERROR BankDaoJdbc:56 - com.revature.project0.Project_0_DClarkyD.ClassLauncher.main(ClassLauncher.java:10)
2018-08-20 16:31:22 WARN  BankDaoJdbc:58 - failed to create new user
2018-08-20 16:31:23 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 16:33:23 ERROR BankDaoJdbc:55 - No value specified for parameter 1.
2018-08-20 16:33:23 ERROR BankDaoJdbc:57 - org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:257)
2018-08-20 16:33:23 ERROR BankDaoJdbc:57 - org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:290)
2018-08-20 16:33:23 ERROR BankDaoJdbc:57 - org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
2018-08-20 16:33:23 ERROR BankDaoJdbc:57 - org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
2018-08-20 16:33:23 ERROR BankDaoJdbc:57 - org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
2018-08-20 16:33:23 ERROR BankDaoJdbc:57 - org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)
2018-08-20 16:33:23 ERROR BankDaoJdbc:57 - com.revature.daos.BankDaoJdbc.createUser(BankDaoJdbc.java:42)
2018-08-20 16:33:23 ERROR BankDaoJdbc:57 - com.revature.project0.Project_0_DClarkyD.RegisterGuest.start(RegisterGuest.java:38)
2018-08-20 16:33:23 ERROR BankDaoJdbc:57 - com.revature.project0.Project_0_DClarkyD.ClassLauncher.main(ClassLauncher.java:10)
2018-08-20 16:33:23 WARN  BankDaoJdbc:59 - failed to create new user
2018-08-20 16:33:24 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 16:37:08 WARN  BankDaoJdbc:84 - failed to find user with provided credentials from the db
2018-08-20 16:37:22 ERROR BankDaoJdbc:56 - ResultSet not positioned properly, perhaps you need to call next.
2018-08-20 16:37:22 ERROR BankDaoJdbc:58 - org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2768)
2018-08-20 16:37:22 ERROR BankDaoJdbc:58 - org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2046)
2018-08-20 16:37:22 ERROR BankDaoJdbc:58 - org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2481)
2018-08-20 16:37:22 ERROR BankDaoJdbc:58 - com.revature.daos.BankDaoJdbc.createUser(BankDaoJdbc.java:45)
2018-08-20 16:37:22 ERROR BankDaoJdbc:58 - com.revature.project0.Project_0_DClarkyD.RegisterGuest.start(RegisterGuest.java:38)
2018-08-20 16:37:22 ERROR BankDaoJdbc:58 - com.revature.project0.Project_0_DClarkyD.ClassLauncher.main(ClassLauncher.java:10)
2018-08-20 16:37:22 WARN  BankDaoJdbc:60 - failed to create new user
2018-08-20 16:37:22 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 16:42:50 ERROR BankDaoJdbc:57 - ResultSet not positioned properly, perhaps you need to call next.
2018-08-20 16:42:50 ERROR BankDaoJdbc:59 - org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2768)
2018-08-20 16:42:50 ERROR BankDaoJdbc:59 - org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2046)
2018-08-20 16:42:50 ERROR BankDaoJdbc:59 - org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2481)
2018-08-20 16:42:50 ERROR BankDaoJdbc:59 - com.revature.daos.BankDaoJdbc.createUser(BankDaoJdbc.java:45)
2018-08-20 16:42:50 ERROR BankDaoJdbc:59 - com.revature.project0.Project_0_DClarkyD.RegisterGuest.start(RegisterGuest.java:38)
2018-08-20 16:42:50 ERROR BankDaoJdbc:59 - com.revature.project0.Project_0_DClarkyD.ClassLauncher.main(ClassLauncher.java:10)
2018-08-20 16:42:50 WARN  BankDaoJdbc:61 - failed to create new user
2018-08-20 16:42:50 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 16:46:09 ERROR BankDaoJdbc:55 - ResultSet not positioned properly, perhaps you need to call next.
2018-08-20 16:46:09 ERROR BankDaoJdbc:57 - org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2768)
2018-08-20 16:46:09 ERROR BankDaoJdbc:57 - org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2046)
2018-08-20 16:46:09 ERROR BankDaoJdbc:57 - org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2481)
2018-08-20 16:46:09 ERROR BankDaoJdbc:57 - com.revature.daos.BankDaoJdbc.createUser(BankDaoJdbc.java:44)
2018-08-20 16:46:09 ERROR BankDaoJdbc:57 - com.revature.project0.Project_0_DClarkyD.RegisterGuest.start(RegisterGuest.java:38)
2018-08-20 16:46:09 ERROR BankDaoJdbc:57 - com.revature.project0.Project_0_DClarkyD.ClassLauncher.main(ClassLauncher.java:10)
2018-08-20 16:46:09 WARN  BankDaoJdbc:59 - failed to create new user
2018-08-20 16:46:09 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 16:49:37 ERROR BankDaoJdbc:61 - ERROR: column "user_id" of relation "bank_transactions" does not exist
  Position: 31
2018-08-20 16:49:37 ERROR BankDaoJdbc:63 - org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
2018-08-20 16:49:37 ERROR BankDaoJdbc:63 - org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
2018-08-20 16:49:37 ERROR BankDaoJdbc:63 - org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
2018-08-20 16:49:37 ERROR BankDaoJdbc:63 - org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
2018-08-20 16:49:37 ERROR BankDaoJdbc:63 - org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
2018-08-20 16:49:37 ERROR BankDaoJdbc:63 - org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
2018-08-20 16:49:37 ERROR BankDaoJdbc:63 - org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
2018-08-20 16:49:37 ERROR BankDaoJdbc:63 - com.revature.daos.BankDaoJdbc.createUser(BankDaoJdbc.java:56)
2018-08-20 16:49:37 ERROR BankDaoJdbc:63 - com.revature.project0.Project_0_DClarkyD.RegisterGuest.start(RegisterGuest.java:38)
2018-08-20 16:49:37 ERROR BankDaoJdbc:63 - com.revature.project0.Project_0_DClarkyD.ClassLauncher.main(ClassLauncher.java:10)
2018-08-20 16:49:37 WARN  BankDaoJdbc:65 - failed to create new user
2018-08-20 16:49:38 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 16:51:14 WARN  BankDaoJdbc:87 - failed to find user with provided credentials from the db
2018-08-20 16:51:28 TRACE BankDaoJdbc:56 - 1 records created
2018-08-20 16:51:28 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 16:51:39 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 16:51:40 TRACE HistoryDaoJdbc:29 - 2 records created
2018-08-20 16:55:24 TRACE BankDaoJdbc:57 - 1 records created
2018-08-20 16:55:25 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 16:55:38 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 16:55:39 TRACE HistoryDaoJdbc:29 - 3 records created
2018-08-20 17:28:58 TRACE BankDaoJdbc:57 - 1 records created
2018-08-20 17:28:59 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 17:29:09 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 17:29:10 TRACE HistoryDaoJdbc:29 - 3 records created
2018-08-20 17:33:10 TRACE BankDaoJdbc:58 - 1 records created
2018-08-20 17:33:10 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 17:33:23 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 17:33:24 TRACE HistoryDaoJdbc:29 - 3 records created
2018-08-20 17:38:04 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 17:38:05 TRACE HistoryDaoJdbc:29 - 2 records created
2018-08-20 18:53:44 WARN  HistoryDaoJdbc:111 - failed to find user with provided credentials from the db
2018-08-20 18:53:54 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 18:53:55 TRACE HistoryDaoJdbc:29 - 3 records created
2018-08-20 18:54:13 TRACE HistoryDaoJdbc:29 - 3 records created
2018-08-20 19:00:09 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 19:00:09 TRACE HistoryDaoJdbc:29 - 4 records created
2018-08-20 19:00:29 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 19:00:30 TRACE HistoryDaoJdbc:29 - 5 records created
2018-08-20 19:00:43 WARN  HistoryDaoJdbc:111 - failed to find user with provided credentials from the db
2018-08-20 19:01:22 WARN  HistoryDaoJdbc:111 - failed to find user with provided credentials from the db
2018-08-20 19:41:35 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 19:41:35 TRACE HistoryDaoJdbc:29 - 6 records created
2018-08-20 19:41:48 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 19:41:48 TRACE HistoryDaoJdbc:29 - 7 records created
2018-08-20 19:43:57 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 19:43:58 TRACE HistoryDaoJdbc:29 - 8 records created
2018-08-20 19:44:08 TRACE HistoryDaoJdbc:53 - 1 records created
2018-08-20 19:44:09 TRACE HistoryDaoJdbc:29 - 9 records created
2018-08-20 19:58:49 TRACE HistoryDaoJdbc:54 - 1 records created
2018-08-20 19:59:11 TRACE HistoryDaoJdbc:54 - 1 records created
2018-08-20 19:59:56 TRACE HistoryDaoJdbc:55 - 1 records created
2018-08-20 19:59:57 TRACE HistoryDaoJdbc:31 - 1 records created
2018-08-20 20:01:44 TRACE HistoryDaoJdbc:55 - 1 records created
2018-08-20 20:01:44 TRACE HistoryDaoJdbc:31 - 1 records created
2018-08-20 20:02:26 WARN  HistoryDaoJdbc:122 - failed to find user with provided credentials from the db
2018-08-20 20:02:32 TRACE HistoryDaoJdbc:55 - 1 records created
2018-08-20 20:02:33 TRACE HistoryDaoJdbc:31 - 1 records created
2018-08-20 20:03:09 TRACE BankDaoJdbc:58 - 1 records created
2018-08-20 20:03:09 TRACE HistoryDaoJdbc:55 - 1 records created
2018-08-20 20:03:30 TRACE HistoryDaoJdbc:55 - 1 records created
2018-08-20 20:03:31 TRACE HistoryDaoJdbc:31 - 1 records created
2018-08-20 20:05:41 TRACE BankDaoJdbc:58 - 1 records created
2018-08-20 20:05:41 TRACE HistoryDaoJdbc:55 - 1 records created
2018-08-20 20:05:54 TRACE HistoryDaoJdbc:31 - 1 records created
2018-08-20 20:08:45 TRACE HistoryDaoJdbc:31 - 1 records created
2018-08-20 20:12:53 TRACE BankDaoJdbc:58 - 1 records created
2018-08-20 20:12:53 TRACE HistoryDaoJdbc:55 - 1 records created
2018-08-20 20:13:20 WARN  HistoryDaoJdbc:122 - failed to find user with provided credentials from the db
2018-08-20 20:13:31 TRACE HistoryDaoJdbc:31 - 1 records created
2018-08-20 20:14:55 WARN  BankDaoJdbc:89 - failed to find user with provided credentials from the db
2018-08-20 20:15:04 TRACE BankDaoJdbc:58 - 1 records created
2018-08-20 20:15:14 TRACE HistoryDaoJdbc:31 - 1 records created
2018-08-20 20:22:15 WARN  HistoryDaoJdbc:153 - failed to find user with provided credentials from the db
2018-08-20 20:22:16 TRACE HistoryDaoJdbc:31 - 1 records created
2018-08-20 20:24:03 TRACE HistoryDaoJdbc:31 - 1 records created
2018-08-20 20:24:57 TRACE HistoryDaoJdbc:31 - 1 records created
2018-08-20 20:49:35 TRACE HistoryDaoJdbc:31 - 1 records created
2018-08-20 20:50:02 WARN  BankDaoJdbc:89 - failed to find user with provided credentials from the db
2018-08-20 20:50:11 TRACE HistoryDaoJdbc:31 - 1 records created
2018-08-20 20:50:38 TRACE HistoryDaoJdbc:31 - 1 records created
2018-08-20 20:52:11 TRACE HistoryDaoJdbc:31 - 1 records created
2018-08-20 20:52:24 TRACE HistoryDaoJdbc:31 - 1 records created
2018-08-20 20:58:17 WARN  BankDaoJdbc:89 - failed to find user with provided credentials from the db
2018-08-20 20:58:26 TRACE BankDaoJdbc:58 - 1 records created
2018-08-20 20:58:35 WARN  HistoryDaoJdbc:154 - failed to find user with provided credentials from the db
2018-08-21 08:00:04 WARN  BankDaoJdbc:89 - failed to find user with provided credentials from the db
2018-08-21 08:00:20 WARN  HistoryDaoJdbc:154 - failed to find user with provided credentials from the db
2018-08-21 08:00:20 TRACE HistoryDaoJdbc:31 - 1 records created
2018-08-21 08:02:10 WARN  BankDaoJdbc:89 - failed to find user with provided credentials from the db
2018-08-21 08:02:35 TRACE HistoryDaoJdbc:31 - 1 records created
2018-08-21 08:29:00 TRACE HistoryDaoJdbc:31 - 1 records created
2018-08-21 08:29:17 WARN  BankDaoJdbc:89 - failed to find user with provided credentials from the db
2018-08-21 08:29:18 WARN  HistoryDaoJdbc:122 - failed to find user with provided credentials from the db
2018-08-21 08:29:24 TRACE HistoryDaoJdbc:31 - 1 records created
